# Generated by Django 5.0.7 on 2024-09-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_category_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
