# Generated by Django 5.0.7 on 2024-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_book_amount_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amount_available',
            field=models.IntegerField(default=0),
        ),
    ]
